### ISSUE TITLE
Allow to override a particular value (--set command line)

### ISSUE THREAD

**Issue by lzaldivarkt** [tmc/rules_helm#2]
It would be great to have the option to set an individual value and not relying only on the values file.

**Comment by tmc** [comment]
@lzaldivarkt I agree -- one way to do this would be to introduce a map argument of keypath to values -- can you think of a better api?

**Comment by lzaldivarkt** [comment]
That sound good to me.

Also, helm has a specificity order that it would be nice to respect.

https://github.com/helm/helm/blob/master/docs/chart_template_guide/values_files.md

**Comment by tmc** [comment]
Implemented as of https://github.com/tmc/rules_helm/commit/a5da938887dfa844e4b907152d27df0bd99a1d8f and tagged as 0.3.0. Example updated at https://github.com/tmc/rules_helm_example/blob/master/BUILD#L25
